# Generated by Django 5.2.9 on 2025-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
