# Generated by Django 5.2.9 on 2025-12-16 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='tickets',
                                             to='flights.flight')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='tickets',
                                            to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row',
                                                                'seat', 'flight'),
                                                        name='unique_seat_per_flight')],
            },
        ),
    ]
